import { CategoryType, type Prisma } from "@prisma/client";

export const defaultCategories = [
  {
    code: "FOOD",
    name: "Comida",
    type: CategoryType.EXPENSE,
    color: "#F97316",
    icon: "utensils",
    isSystem: true,
    sortOrder: 1,
  },
  {
    code: "TRANSPORT",
    name: "Transporte",
    type: CategoryType.EXPENSE,
    color: "#3B82F6",
    icon: "car",
    isSystem: true,
    sortOrder: 2,
  },
  {
    code: "SERVICES",
    name: "Servicios",
    type: CategoryType.EXPENSE,
    color: "#8B5CF6",
    icon: "receipt",
    isSystem: true,
    sortOrder: 3,
  },
  {
    code: "HEALTH",
    name: "Salud",
    type: CategoryType.EXPENSE,
    color: "#EF4444",
    icon: "heart-pulse",
    isSystem: true,
    sortOrder: 4,
  },
  {
    code: "ENTERTAINMENT",
    name: "Entretenimiento",
    type: CategoryType.EXPENSE,
    color: "#EC4899",
    icon: "gamepad-2",
    isSystem: true,
    sortOrder: 5,
  },
  {
    code: "SHOPPING",
    name: "Compras",
    type: CategoryType.EXPENSE,
    color: "#06B6D4",
    icon: "shopping-bag",
    isSystem: true,
    sortOrder: 6,
  },
  {
    code: "OTHER_EXPENSE",
    name: "Otro",
    type: CategoryType.EXPENSE,
    color: "#6B7280",
    icon: "circle-help",
    isSystem: true,
    sortOrder: 99,
  },
  {
    code: "SALARY",
    name: "Salario",
    type: CategoryType.INCOME,
    color: "#16A34A",
    icon: "wallet",
    isSystem: true,
    sortOrder: 1,
  },
  {
    code: "FREELANCE",
    name: "Freelance",
    type: CategoryType.INCOME,
    color: "#14B8A6",
    icon: "briefcase-business",
    isSystem: true,
    sortOrder: 2,
  },
  {
    code: "OTHER_INCOME",
    name: "Otro ingreso",
    type: CategoryType.INCOME,
    color: "#6B7280",
    icon: "circle-plus",
    isSystem: true,
    sortOrder: 99,
  },
] satisfies Prisma.CategoryCreateWithoutUserInput[];
